### ISSUE TITLE
if the list is long, the whole page can not be displayed well.

### ISSUE THREAD

**Issue by archonwang** [heriet/redmine-selectbox-autocompleter#2]
@heriet , as you see, if the list is long, the whole page can not be displayed well. please check it to add scrollbar. thanks.
![default](https://cloud.githubusercontent.com/assets/834512/21632305/e47ebe76-d27f-11e6-8584-c5521eac216a.png)

**Comment by heriet** [comment]
thanks for issue. I see. But, I have no plans to change that now.

Because, autocomplete(html5) UI depends on the browser implementation.
For example, long datalist autocomplete displays scrollbar well in Firefox. But Chrome not.

If you need more rich autocomplete for selectbox, try other plugins (ex. autocomplete implemented by Select2).

- https://github.com/Restream/redmine__select2
- https://github.com/Restream/redmine_simple
- https://github.com/Restream/redmine_customize
 
- https://github.com/ries-tech/redmine_improved_searchbox

**Comment by heriet** [comment]
Yesterday, I wrote "no plan", but i'll do it.
I will add Select2 mode. maybe easy.

**Comment by archonwang** [comment]
@heriet , Thanks.

**Comment by heriet** [comment]
@archonwang updated 1.1.0. try it.
